<?php
/**
 * Website:	http://www.grsoftware.in/
 * Contributions by	:
 *		Gopal Grover	(Developer)
 *
 * @author GR Software <developer@grsoftware.in>
 *
 *******************************************************
 UNLESS YOU KNOW HOW TO CODE, DO NOT EDIT THIS FILE!!!!
 *******************************************************
 								|     |
                                \\_V_//
                                \/=|=\/
                                 [=v=]
                               __\___/_____
                              /..[  _____  ]
                             /_  [ [  M /] ]
                            /../.[ [ M /@] ]
                           <-->[_[ [M /@/] ]
                          /../ [.[ [ /@/ ] ]
     _________________]\ /__/  [_[ [/@/ C] ]
    <_________________>>0---]  [=\ \@/ C / /
       ___      ___   ]/000o   /__\ \ C / /
          \    /              /....\ \_/ /
       ....\||/....           [___/=\___/
      .    .  .    .          [...] [...]
     .      ..      .         [___/ \___]
     .    0 .. 0    .         <---> <--->
  /\/\.    .  .    ./\/\      [..]   [..]
 / / / .../|  |\... \ \ \    _[__]   [__]_
/ / /       \/       \ \ \  [____>   <____]
*******************************************************
    (_\     /_)
       ))   ((
     .-"""""""-.
 /^\/  _.   _.  \/^\
 \(   /__\ /__\   )/
  \,  \o_/_\o_/  ,/
    \    (_)    /
     `-.'==='.-'
      __) - (__
     /  `~~~`  \
    /  /     \  \
    \ :       ; /
     \|==(*)==|/
      :       :
       \  |  /
     ___)=|=(___
	{____/ \____}

YOU ARE NOT LISTENING
*******************************************************
             .-----.
            /       `\
          _|_         |
         /   \        | 
         '==='        |


         . ' .        |
        . : ' .       |
           '.         |
       . '    .       |
        .-"""-.       |
       /  \___ \      |
       |/`    \|      |
       (  a  a )      |
       |   _\ |       |
       )\  =  /       |
   _.-'  '---;        |
 /`           `-.     |
|                \    |
|    |   .  & .   \   |
\    /      &   |  ;  |
|   |           |  ;  |
|   /\          /  |  |
\   \ )   -:-  /\  \  |
 `.  `-.  -:-  | \  \_|
   '-.  `-.    (  './\`\
    / `'-. `\  |    \/_/
    |    \  |  |      |
    |    /'-\  /      |
     \   \   | |      |
      \   )_/\ |      |
       \      \|      |
        \      \      |
         '.     |     |
           /   /      |
          /  .';      |
        /`  /  |      |
       /   /   |      |
      |  .' \  |      |
      /  \  )  |      |
      \   \ /  '-.._  |
       '.ooO\__._.Ooo |

HEY YOU! GET OUT!!!
*********************************************************/

declare(strict_types = 1);

use GRSOFTWARES\GRPLUGIN\CONSTANTS as CONSTANT;
use GRSOFTWARES\MODULE\DB as DB;
use GRSOFTWARES\MODULE\MIMETYPE\BASE as MIME;
use GRSOFTWARES\MODULE\OS_CLIENT as OS_CLIENT;
use GRSOFTWARES\MODULE\GR_UTILITY as GR_UTILITY;

/**
 * Very important include
 */
$root = dirname(__DIR__);
require_once($root . '/constant/constant.php');


/**
 * classes loader
 */
require_once($root . '/classes/DB/Db.class.php');
require_once($root . '/classes/MimeType.class.php');
require_once($root . '/classes/GR_OSClient.class.php');
require_once($root . '/classes/GR_Utility.class.php');

$grUtility = new GR_Utility\GR_Utility(DEBUG, "7.4");

function grUtilityCompress($buff) : string {
	global $grUtility;
	return $grUtility->grCompress($buff);
}

$getMimeType = fn($ext) =>  MIME\MimeType::getMimeFromExtensionForHeader($ext);

function getOSClient($param) {

	$track = new OS_CLIENT\GR_OSClient();

	switch($param) {
		case "ip":
			return $track->get_ip();
		case "os":
			return $track->getOS();
		case "browser":
			return $track->getBrowser();
		default:
			return false;
	}
}

/**
 * DB Connection
 */
$grdb = $grmydb = $grpgdb = null;

if (USE_MYSQL) {

	$grmydb = new DB\DB(
					array(
						"mysql"	=> array(
							'host'		=> _MYSQL_DB_HOST
							, 'user'	=> _MYSQL_DB_USER
							, 'password'=> _MYSQL_DB_PASS
							, 'dbname'	=> _MYSQL_DB_NAME
							, 'charset'	=> _MYSQL_DB_CHARSET
							, 'port'	=> _MYSQL_DB_PORT
							, 'collation'	=> _MYSQL_DB_COLLATION
						)
					));
}

if (USE_PGSQL) {

	$grpgdb = new DB\DB(
					array(
						"pgsql"	=> array(
							'host'		=> _PGSQL_DB_HOST
							, 'user'	=> _PGSQL_DB_USER
							, 'password'=> _PGSQL_DB_PASS
							, 'dbname'	=> _PGSQL_DB_NAME
							, 'charset'	=> _PGSQL_DB_CHARSET
							, 'port'	=> _PGSQL_DB_PORT
							, 'collation'	=> _PGSQL_DB_COLLATION
						)
					));
}

if (USE_ONLY_ONE_SQL_SERVER && (USE_MYSQL xor USE_PGSQL)) {
	$grdb = (USE_MYSQL) ? $grmydb : $grpgdb;
} else if (USE_MYSQL && USE_PGSQL) {

	$grdb["mysql"] = $grmydb;
	$grdb["pgsql"] = $grpgdb;
}

/**
 * Version Check: MySQL
 */
if (!is_null($grmydb)) {

	$getMySQLVersion = $grmydb->query('select version()')[0]["version()"];
	if (version_compare($getMySQLVersion,  "5.4.0") < 0) {
		die("Required at least MySQL version 5.4.0, your version: $getMySQLVersion");
	}
	unset($getMySQLVersion);
}

/**
 * Version Check: PgSQL
 */
if (!is_null($grpgdb)) {

	$getPgSQLVersion = $grpgdb->query("show server_version")[0]["server_version"];
	if (version_compare($getPgSQLVersion,  "9.6.0") < 0) {
		die("Required at least Postgres SQL version 9.6.0, your version: $getPgSQLVersion");
	}
	unset($getPgSQLVersion);
}

/**
 * Starting a Session
 */
if (session_status() == PHP_SESSION_NONE) {
    session_start();
} else {
	die("Something went wrong with your session. Kindly contact developer");
}
